### ISSUE TITLE
Beautiful repository

### ISSUE THREAD

**Issue by prodigga** [pschraut/UnityTexture2DArrayImportPipeline#1]
Not an issue, but I wanted to say that this is a beautiful repository. Feels like a native extension to Unity.

**Comment by pschraut** [comment]
Thanks so much for the kind words!

My main goal was that it should feel like it's part of Unity. The integration inside the editor (UI/UX), but also from a source code point of view. 

I'm not 100% certain whether the source code conforms to Unity Technologies internal standards and guidelines, but I've tried to write it in a way as code looks like in their [Unity C# reference source code](https://github.com/Unity-Technologies/UnityCsReference) to me.
