### ISSUE TITLE
Texture Quality Half Res and generating Texture2DArray

### ISSUE THREAD

**Issue by HartMagic** [pschraut/UnityTexture2DArrayImportPipeline#5]
Texture2DArray importer vesion: 1.3.0
Unity version: 2020.3.23f1
Texture Quality (in Quality Settings): Half Res

For example:
![2021-12-14_17-36-52](https://user-images.githubusercontent.com/26055406/146018780-8a30bb59-2b90-4c22-a6ab-acfbefde96a3.png)

**Expected behaviour**: Texture2DArray generates without errors.
**Current behaviour**: Texture2DArray generates with Graphics.CopyTexture exception: "source and destination have different master texture limits. Soruce 1, Destination 0" and doesn't work.
![2021-12-14_17-35-10](https://user-images.githubusercontent.com/26055406/146018411-25ca6b7e-66c0-410e-9d12-b115a467f26e.png)
![2021-12-14_17-35-16](https://user-images.githubusercontent.com/26055406/146018432-4095ed4e-e07a-4823-9ad6-85711ab05adb.png)

**Comment by pschraut** [comment]
Hello HartMagic, thank you for the bug-report. It looks like it's the same problem as issue #4. I'll close your report to avoid duplicates.
